// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oroganeqpnpsxuckmrqa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9yb2dhbmVxcG5wc3h1Y2ttcnFhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2ODcwMzksImV4cCI6MjA2NTI2MzAzOX0.3gq9aM0BDu21W2D2uL7GElVH9NXYWsq26UtuJV55DU0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);