// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://thmdyogosswcxdkqsqnz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRobWR5b2dvc3N3Y3hka3FzcW56Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5NjU2MjAsImV4cCI6MjA2NDU0MTYyMH0.F0wtD_XMLayoToknQTU8DFHknhK9h2b3Bh42dvEJuIg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);